### PR TITLE
fix: Error while scrolling when encapsulated in shadow DOM

### LINKED ISSUE #2271: Error while scrolling when encapsulated in shadow DOM
**Describe the bug**
The following error message will be displayed while scolling when the component is used within a component with `encapsulation: ViewEncapsulation.ShadowDom`:

```
Error: e.target is null
```

**Reproducbile example**
[https://stackblitz.com/edit/angular-ga2nur?file=src%2Fdata-source-array-example.component.ts](https://stackblitz.com/edit/angular-ga2nur?file=src%2Fdata-source-array-example.component.ts)

**Desktop:**
 - OS: Windows
 - Browser: Firefox, Chrome
 - ng-select version: v11.1.1

### PR DESCRIPTION
**Pull request by eloyortiz**
Issue: #2271

### CODE REVIEW

**Review by Kowjako — APPROVED** [review]

**Comment by Kowjako** [comment]
@pavankjadda Hi, get this PR merged please, its essential fix, because currently our production system throws a lot of errors "cannot reading property of null (reading scrollTop)"

**Comment by eloyortiz** [comment]
@pavankjadda Hi, get this PR merged please, its essential fix, because currently our production system throws a lot of errors "cannot reading property of null (reading scrollTop)"

**Review by pavankjadda — APPROVED** [review]
LGTM

**Comment by davidoween** [comment]
I have this problem in versión 10. It is fixed?

**Comment by eloyortiz** [comment]
> I have this problem in versión 10. It is fixed?

This PR was merged yesterday... I think you'll have to wait to next release

**Comment by davidoween** [comment]
> > I have this problem in versión 10. It is fixed?
> 
> This PR was merged yesterday... I think you'll have to wait to next release

When will it be approximately?Will it be included in version 10.x.x?

**Comment by mahipureti** [comment]
> > > I have this problem in versión 10. It is fixed?
> > 
> > 
> > This PR was merged yesterday... I think you'll have to wait to next release
> 
> When will it be approximately?Will it be included in version 10.x.x?

It's included in latest version 12.0.5

**Comment by davidoween** [comment]
But what about support for 10.x.x versions? 😔

**Pull request merged**
