### PR TITLE
feat: Feature/1528 select all

### PR DESCRIPTION
**Pull request by slavede**

### CODE REVIEW

**Comment by koreem** [comment]
Nice PR! Will this work when you performed a search and you want to do a select-all on your search results?

**Comment by slavede** [comment]
Yeah, it does select all on currently filtered items.

**Comment by slavede** [comment]
Oh I see...well, if that's the case, we don't need this one. I just though it would be nice feature to have out of the box.

**Comment by tuxflo** [comment]
May I ask why this PR was closed unmerged? Looks like a good feature/improvement to me.

**Comment by vishnu-dev** [comment]
@varnastadeus Why is this closed? This is a very good feature.

**Pull request closed without merging**
