### PR TITLE
feat: upgrade to angular 12

### LINKED ISSUE #1901: Upgrade to Angular 12
**Is your feature request related to a problem? Please describe.**
This package causes peer dependency issues on Angular 12, but the component seems to work fine if I force the warnings.

**Describe the solution you'd like**
Update the peer dependencies, maybe looking into converting it into an Ivy Component

### PR DESCRIPTION
**Pull request by david-shortman**
Fixes #1901

### CODE REVIEW

**Comment by david-shortman** [comment]
Looks like the GitHub action to build needs to be updated to use Node v12 for the angular/animations package.

**Comment by varnastadeus** [comment]
@david-shortman can you update ci workflow with newer node version? https://github.com/ng-select/ng-select/blob/master/.github/workflows/ci.yml#L20

**Comment by david-shortman** [comment]
> @david-shortman can you update ci workflow with newer node version? https://github.com/ng-select/ng-select/blob/master/.github/workflows/ci.yml#L20

Done. Thanks for catching that!

**Comment by Tea-Ice** [comment]
Is there still anything preventing this from being deployed?

**Comment by Tea-Ice** [comment]
@varnastadeus Can you please merge this in?

**Comment by aintnomoreloyalty** [comment]
Hi there
Any update on this?

**Comment by Tea-Ice** [comment]
@anjmao Would you be able to review and release this?

**Review by varnastadeus — APPROVED** [review]

**Comment by enekonieto** [comment]
Thank you very much!

Readme should be updated, new version doesn't appear in [Versions](https://github.com/ng-select/ng-select#versions) section.

**Comment by Maransatto** [comment]
Hi!

I'm still having the error as if this version did not accept angular 12 yet.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: web-odonto@0.4.0
npm ERR! Found: @angular/common@12.0.4
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~12.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">=11.0.0 <12.0.0" from @ng-select/ng-select@7.0.0
npm ERR! node_modules/@ng-select/ng-select
npm ERR!   @ng-select/ng-select@"7.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/maransatto/.npm/eresolve-report.txt for a full report.
```

**Comment by Jooraz** [comment]
Well this is most most likely caused by ng-boostrap reference as they still haven't updated to Angular 12

**Pull request merged**
