### PR TITLE
feat: toggle the dropdown arrow visibility

### LINKED ISSUE #1517: Ability to toggle the visibility of the dropdown arrow
**Is your feature request related to a problem? Please describe.**
I have a basic need to be able to show or hide the dropdown arrow programmatically.

**Describe the solution you'd like**
Similar to how the [clear 'x' in the input can be toggled off](https://github.com/ng-select/ng-select/blob/ae8a04051f4054258714f0bddff84199c5458491/src/ng-select/lib/ng-select.component.html#L59), I want to be able to toggle the arrow in the same way.

**Describe alternatives you've considered**
I have tried [setting CSS as described here](https://github.com/ng-select/ng-select/issues/544#issuecomment-389168319), but that does not seem to work. Alternatively, I also tried using `::ng-deep` but that didn't work either, and looks like it is [planned to be removed from Angular](https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep) in the future.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by TheSamsterZA**
Resolves #1517.

### CODE REVIEW

**Comment by TheSamsterZA** [comment]
@anjmao @varnastadeus please review. There does seem to be some interest in this feature.

**Comment by Lakston** [comment]
I would have liked this feature, I'm currently trying to hide the arrow too.

**Comment by TheSamsterZA** [comment]
@Lakston I figured out how to hide the arrow using CSS and [posted my solution here](https://github.com/ng-select/ng-select/issues/1517#issuecomment-592936052). Hopefully that helps you out.

**Comment by Lakston** [comment]
Thanks @TheSamsterZA , I saw your solution and I'm probably going to use it but I just wanted to up the demand for a more "official solution" :)

**Pull request closed without merging**
