### PR TITLE
Fix Issue #1317 (Uncaught TypeError: Cannot read property 'scrollTop' of null) 

### PR DESCRIPTION
**Pull request by nikunjkonduru**
As discussed in the #1317 , e.path should work for both ViewEncapsulation.ShadowDom and without it instead of e.target.

### CODE REVIEW

**Comment by nikkonduru88** [comment]
@varnastadeus Looks like the test that is failing is an old one. same issue as the PR before this one (#1624).

**Comment by nikkonduru88** [comment]
@varnastadeus all checks are passing now, can you please review the PR when you get a chance. Thank you.

**Comment by nikkonduru88** [comment]
@varnastadeus Hi. Hope you are doing well. Is there any timeline on when this PR can me be reviewed and merged? Thank you.

**Comment by nikunjkonduru** [comment]
@varnastadeus Hi we need this fix before the update to Angular 10. Is it possible to merge this before that? Thank you.

**Pull request closed without merging**
