### PR TITLE
fix(ng-option): Remove event emits full ng-select model instead of direct value

### LINKED ISSUE #2288: Remove event emits full ng-select model instead of direct value
**Describe the bug**
It seems like the `remove` event emits the whole `NgOption` object instead of its value property. 

**To Reproduce** 
1. Select an arbitrary item
2. Deselect previously selected element
3. Inspect emitted value from (remove) event.

**Expected behavior**
I would expect that the value emitted from the remove event should contain direct value of the item passed by the user to the items array - the same structure as its counter part `add` event emits.

### PR DESCRIPTION
**Pull request by emir7**
A potential solution for the following issue: #2288

### CODE REVIEW

**Review by pavankjadda — APPROVED** [review]
LGTM

**Comment by pavankjadda** [comment]
@emir7 Can you check the CI and update accordingly?

**Comment by emir7** [comment]
@pavankjadda will do

**Comment by emir7** [comment]
@pavankjadda seems like there was one more occurrence where onRemove was called inside the tests and had to be updated

**Pull request merged**
