### PR TITLE
updated peerDependencies to allow angular 15.*

### PR DESCRIPTION
**Pull request by luke1992**

### CODE REVIEW

**Comment by luke1992** [comment]
#2168

**Review by varnastadeus — APPROVED** [review]

**Comment by jpike88** [comment]
aww yiss

**Comment by tiro-reflact** [comment]
@varnastadeus Any chances the updated dependencies for ng-option-highlight will get published to npm?

**Comment by kamilchlebek** [comment]
@varnastadeus kind reminder ;)

**Comment by loonix** [comment]
any update on this guys?

**Pull request merged**
