### PR TITLE
chore: update ng-select to support angular v9 (#1499)

### PR DESCRIPTION
**Pull request by wclaibor**

### CODE REVIEW

**Comment by gongAll** [comment]
Would make sense to update angular to the stabler version 9.1.0 before merging.

**Comment by steve-todorov** [comment]
@varnastadeus ping - what's the state of this PR? It looks like @wclaibor has already done the work. Could we get this merged and released any time soon? :)

**Comment by anjmao** [comment]
Hi, I will test it tomorrow and if it works make a release :) @wclaibor thanks a lot 👍

**Comment by steve-todorov** [comment]
Awesome! Thanks! :)

**Pull request merged**
