### PR TITLE
resolve drop down panel text align in rtl mode

### PR DESCRIPTION
**Pull request by MetaiR**

### CODE REVIEW

**Comment by MetaiR** [comment]
does it usually take this much for a simple pull request to be merged?

**Comment by varnastadeus** [comment]
@MetaiR can you create issue describing the problem? Just changing the code doesn't help a lot

**Comment by MetaiR** [comment]
@varnastadeus #871

**Comment by anjmao** [comment]
@MetaiR Thanks for a fix 👍

**Pull request merged**
