### PR TITLE
feat: add boolean and number transformers

### PR DESCRIPTION
**Pull request by Dafnik**
adding to ng-dropdown-panel, ng-option and ng-select

### CODE REVIEW

**Comment by pavankjadda** [comment]
@Dafnik what does this acheive?

**Comment by Dafnik** [comment]
Ohh, sorry for not explaining earlier. 

It allows boolean and number inputs to passed like a string.
```html
<ng-select-example multiple="true" />
// Instead of
<ng-select-example [multiple]="true" />
```
or even just
```html
<ng-select-example multiple />
```
to set a boolean to true.

The docs are really none-existent on this.
https://angular.io/api/core/booleanAttribute
https://angular.io/api/core/numberAttribute

**Comment by pavankjadda** [comment]
@Dafnik can you rabase with master and fix conflicts

**Review by pavankjadda — CHANGES_REQUESTED** [review]
can you rebase with master and fix conflicts?

**Comment by pavankjadda** [comment]
@Dafnik I like the PR. Fix conflicts and push new update

**Review by pavankjadda — APPROVED** [review]

**Pull request merged**
