### PR TITLE
Add bootstrap 4 SCSS file

### PR DESCRIPTION
**Pull request by pierresh**
Following discussion in issue #647 , I created a theme for Bootstrap 4 based on the original SCSS file. Maybe it does not match 100% with Boostrap style but at least the result is satisfying.

### CODE REVIEW

**Comment by varnastadeus** [comment]
@pierresh thank you for contributing. Can you add it to demo page so you could switch between themes dynamically?

**Comment by pierresh** [comment]
Hello, ok I just added it to demo page.

**Comment by ivanpadavan** [comment]
That would be nice to have a scss file that depends on bootstrap variables in dist

**Comment by anjmao** [comment]
@varnastadeus Do you know what is the status of this issue, can we merge it?

**Comment by varnastadeus** [comment]
@anjmao there was few issues when I looked that need to be fixed before merging

**Comment by andrejm7** [comment]
how to use this?

**Comment by shihrer** [comment]
@varnastadeus Do you know what issues there were?  Perhaps someone else can pick this up to finish it off.

**Comment by varnastadeus** [comment]
there were some alignment and focus issues, maybe I will fix them them on weekend

**Comment by fabianedl777** [comment]
how to use this?

**Pull request closed without merging**
