### PR TITLE
build: update package versions

### PR DESCRIPTION
**Pull request by terencehonles**
This change updates the packages @ng-select/* depends on, including the missed @angular-eslint v16 packages, @ng-bootstrap to v15, and finally all other packages, including @angular, are updated to their latest versions.

### CODE REVIEW

**Comment by pavankjadda** [comment]
> This change updates the packages @ng-select/* depends on, including the missed @angular-eslint v16 packages, @ng-bootstrap to v15, and finally all other packages, including @angular, are updated to their latest versions.

This has many unintended changes. Please update PR with only changes not white spaces/blanks.

**Comment by terencehonles** [comment]
> > This change updates the packages @ng-select/* depends on, including the missed @angular-eslint v16 packages, @ng-bootstrap to v15, and finally all other packages, including @angular, are updated to their latest versions.
> 
> This has many unintended changes. Please update PR with only changes not white spaces/blanks.

I don't know if that's possible. I'm not sure what lint rule, if any allowed the existing formatting. I'm under the impression the previous linting didn't understand decorators and everything including the closing brace and parentheses was put at the same under l indent level. Upgrading to the new version looks like it understood things differently and since it's still quite a minimal change I left it in. I tried searching a little for a config option, but didn't spend more than 10-20 minutes, so if you think this should not introduce the whitespace changes and can find the option to keep the lint rules the same I'd welcome the update to the config.

**Comment by pavankjadda** [comment]
> > > This change updates the packages @ng-select/* depends on, including the missed @angular-eslint v16 packages, @ng-bootstrap to v15, and finally all other packages, including @angular, are updated to their latest versions.
> 
> > 
> 
> > This has many unintended changes. Please update PR with only changes not white spaces/blanks.
> 
> 
> 
> I don't know if that's possible. I'm not sure what lint rule, if any allowed the existing formatting. I'm under the impression the previous linting didn't understand decorators and everything including the closing brace and parentheses was put at the same indent level. Upgrading to the new version looks like it understood things differently and since it's still quite a minimal change I left it in. I tried searching a little for a config option, but didn't spend more than 10-20 minutes, so if you think this should not introduce the whitespace changes and can find the option to keep the lint rules the same I'd welcome the update to the config.

That would be helpful. If not close this and create new PR with changes

**Comment by terencehonles** [comment]
I meant if you could find the rule, but I looked at it looks like this is probably related to https://github.com/eslint/eslint/issues/15299 and https://github.com/typescript-eslint/typescript-eslint/issues/1824, but I could not find out how to change the rule and I'm not sure it's worth the effort. I'm not sure what change you're requesting I make to this PR. Are you requesting that I update eslint separately? I can do that, but the changes are quite minimal (I pulled in some more since I realized eslint:recommended and @eslint-typescript/recommended were not enabled. I turned off a few that would require more changes)

**Pull request closed without merging**
