### PR TITLE
fix: compositionEnd event not fired on mobile chrome. #1451

### LINKED ISSUE #1642: Selected Value not displayed after Filtering on Mobile
**Describe the bug**
When filtering on mobile chrome and then selecting a value, the class `ng-select-filtered` stays on and sets `visibility: hidden` on the selected value. This is due to `(compositionend)="onCompositionEnd(searchInput.value)"` not firing when typing. It only fires when you close the keyboard on mobile which you obviously don't.
**Reproducbile example**
Filter List on mobile then select a value. Value is not visible.

**To Reproduce** 
Steps to reproduce the behavior (if example is not provided):
1. Clone Repo and Run `ng serve --host 0.0.0.0`. Remote Debug your Android device.
2. first dropdown
3. type 'k'
4. select any value, before closing your keyboard

**Expected behavior**
The selected value should be visible after selection.
**Screenshots**
Screenshot 2020-06-07 at 02 16 28

**Smartphone (please complete the following information):**
 - Device: Samsung S10 Plus, OnePlus X
 - OS: android
 - Browser chrome
 - Version latest

**Additional context**
I could fix this by replacing 
`(compositionend)="onCompositionEnd(searchInput.value)"` with
`(input)="onCompositionEnd(searchInput.value)"`in `src/ng-select/lib/ng-select.component.html`

### PR DESCRIPTION
**Pull request by vltansky**
In mobile chrome (latest) compositionEnd inputs event not being called, resulting `_isComposing` variable not to set false, so after selection made - input label `div.ng-value` continue to be hidden, cause `.ng-select-filtered` not removed as it depends on `_isComposing` variable.
Attaching reproduction gif.

compositionEnd event not being called by the browser cause of `(change)="$event.stopPropagation()"` (only in mobile). But the thing is that even if to find the way to fix it and make the event being called - it doesn't fix the bug, as on mobile compositionEnd event calls after the keyboard is closed and not after option selected. So it will still be an empty label until the keyboard won't be closed. Try it [here ](https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionend_event)from mobile.

So I've added `_isComposing = false` into `select()` function to make sure that after option selected, label will be visible. 

ezgif-6-914da063020f

closes #1642 #1451

### CODE REVIEW

**Comment by vltansky** [comment]
@varnastadeus, in my opinion, this is a critical bug. I would be happy if you could review this soon.

Meantime I'm using temporary CSS solution for my project.
`.ng-select.ng-select{
    &.ng-select-single.ng-select-filtered .ng-select-container.ng-has-value .ng-value-container:not(.ng-select-opened){
        .ng-value{
            visibility: visible;
        }
    }
}`
Just in case will be useful for somebody.

**Comment by vesauimonen** [comment]
> Meantime I'm using temporary CSS solution for my project.
> `.ng-select.ng-select.ng-select-single.ng-select-filtered:not(.ng-select-opened) .ng-select-container.ng-has-value .ng-value-container .ng-value{ visibility: visible; }`
> Just in case will be useful for somebody.

Thank you for this!

---

I agree that this is a critical bug. I can also confirm that this PR fixes #1451. I'm happy with this solution, even though it does not address the root issue of `compositionEnd` not being fired.

**Comment by vltansky** [comment]
@anjmao , maybe you could review this, please?

**Comment by Friedrich-Mocker** [comment]
please someone review this =)

**Comment by vltansky** [comment]
@vesauimonen could you review this?

**Comment by vltansky** [comment]
Dont close

**Comment by vltansky** [comment]
closing this. This commit fixed this https://github.com/ng-select/ng-select/commit/cb2a5bc0e2e4f6d26969c6d086e407ed9d25c422

**Pull request closed without merging**
