### PR TITLE
feat(core): adds angular 16 support

### PR DESCRIPTION
**Pull request by pavankjadda**

### CODE REVIEW

**Comment by pavankjadda** [comment]
@varnastadeus please review and approve this

**Comment by varnastadeus** [comment]
> @varnastadeus please review and approve this
@pavankjadda can you check build issues

**Comment by RuMont** [comment]
Node v14 is no longer supported on Angular  v16, try installing Node v16 or 18.

**Comment by pavankjadda** [comment]
> imho the node setup should be on v18 as it is one of the officially supported versions by the framework [angular/angular#49255](https://github.com/angular/angular/pull/49255) and typescript dependency also should be higher than the now deprecated one [angular/angular#49155](https://github.com/angular/angular/pull/49155) as they deleted compatibility code from older versions than 4.9

Correct. I updated node to 18 and TS to 5.0.4

**Comment by RuMont** [comment]
I only got this building by removing @angular-eslint packages, deleting yarn.lock and updating @ng-bootstrap and @types/node to the latest version.

**Comment by ak274** [comment]
As in v16 inputs can be mark as required. IMO items  now should be required.

**Comment by steve3d** [comment]
`items` can not be required, because there are some use cases which only use `ng-option` without `items`

**Comment by nicholasp** [comment]
Please also the ng-option-highlight package

 @angular/common@">=13.0.0 <14.0.0" from @ng-select/ng-option-highlight@0.0.7

**Comment by shessafridi** [comment]
Any update on this ?

**Comment by JKuskys** [comment]
Seems to be working and final, could this be merged @varnastadeus? :)

**Review by varnastadeus — APPROVED** [review]

**Comment by shessafridi** [comment]
Great, please release it on npm so I can stop using --force when installing packages😂

**Pull request merged**
