### PR TITLE
fix: ng-dropdown-panel for a11y improvements

### PR DESCRIPTION
**Pull request by Arhum24**
Changes to "ng-dropdown-panel" for better accessibility as the "American Disability Act" becomes mainstream and other developers may or may not have to comply with it as well in the future.

Tested with VoiceOver on Android 13, change is made so that a screen reader i.e. NVDA, Talkback, or Voiceover would speak the number of items present in a list.

W3C accessibility/a11y patterns state that a dropdown or a list of options should have a role "listbox", as screen readers such as TalkBack (Android's screen reader), VoiceOver (iOS's screen reader), and NVDA (popular desktop screen reader) will state the header and location of each option in the list for a better experience. The link below will explain how it does so with its interactions and properties.

[ARIA ListBox](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/)

### CODE REVIEW

**Comment by Arhum24** [comment]
Hi @anurag-roy, all the checks are green, can this PR be merged ASAP? 🙂

**Comment by anurag-roy** [comment]
I'm not a maintainer of this library @Arhum24

**Comment by pavankjadda** [comment]
@Arhum24 could you add some links related to a11y? Like why did you add 'listbox' role instead of any other role? It will help reviewers and others looking to review the PR

**Comment by Arhum24** [comment]
@pavankjadda, for sure I can add the link to the documentation. 🙂

W3C accessibility/a11y patterns state that a dropdown or a list of options should have a role "listbox", as screen readers such as TalkBack (Android's screen reader), VoiceOver (iOS's screen reader), and NVDA (popular desktop screen reader) will state the header and location of each option in the list for a better experience. The link below will explain how it does so with its interactions and properties.

[ARIA ListBox](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/)

**Review by pavankjadda — APPROVED** [review]

**Pull request merged**
