### PR TITLE
feat: add custom arrow template

### PR DESCRIPTION
**Pull request by rgoupil**
Add a template to customise the dropdown arrow, a cleaner way to solve #544 than with ugly `::ng-deep`

Also remove a few trailing spaces apparently, my IDE just can't help it.
I can put back the dust where it was if you prefer 😛

### CODE REVIEW

**Review by LeonardoBein — APPROVED** [review]

**Review by raju-tagline — APPROVED** [review]

**Comment by rgoupil** [comment]
@raju-tagline I just updated the branch to latest

**Comment by rgoupil** [comment]
@pavankjadda branch updated :)

**Comment by rgoupil** [comment]
@LeonardoBein, @raju-tagline, @pavankjadda any chance we can get this merged? :)

**Comment by pavankjadda** [comment]
#2387 will take care of this

**Pull request closed without merging**
