### PR TITLE
Angular 8 Upgrade

### PR DESCRIPTION
**Pull request by alvaro-octal**
- The project now runs over Angular 8.
- The dependencies have been upgraded.
- NodeJs 10 is now required.

### CODE REVIEW

**Comment by alvaro-octal** [comment]
should be enough to fix https://github.com/ng-select/ng-select/issues/1196, not very confident on whether this PR is correct or not, first time migrating a library.

**Comment by cptwunderlich** [comment]
>     * NodeJs 12 is now required.

Why though? 10.16.0 is currently the active LTS version. Do you need any newer features?
Otherwise it seems pertinent to use the LTS version as a lowest common denominator.
See https://nodejs.org/en/about/releases/

**Comment by alvaro-octal** [comment]
> > ```
> > * NodeJs 12 is now required.
> > ```
> 
> Why though? 10.16.0 is currently the active LTS version. Do you need any newer features?
> Otherwise it seems pertinent to use the LTS version as a lowest common denominator.
> See https://nodejs.org/en/about/releases/

Hi @cptwunderlich ,

I've been searching, and I promise, at some point of Angular 8 node 12 was a requirement. I'm now preparing a downgrade.

**Comment by steve3d** [comment]
still waiting this for my project to upgrade to angular v8, now ng-select is the last blocker for me to upgrade to angular v8.

**Comment by varnastadeus** [comment]
@steve3d if everything works fine just don't mind the warnings

**Pull request closed without merging**
