### PR TITLE
chore(doc): add basic examples to readme

### PR DESCRIPTION
**Pull request by valburyakov**
This PR for #1753. Added small basic examples of usage ng-select to readme file

### CODE REVIEW

**Review by varnastadeus — APPROVED** [review]
⭐

**Comment by jsgoupil** [comment]
```<ng-select [items]="cars" [(ngModel)]="selectedCar"></ng-select>```
Doesn't it select the whole object and not a number in this case?

**Comment by valburyakov** [comment]
> `<ng-select [items]="cars" [(ngModel)]="selectedCar"></ng-select>`
> Doesn't it select the whole object and not a number in this case?
Yeah, you're right, by default it bind the whole object. I'll fix it and also need to fix URL to demo.

**Comment by jsgoupil** [comment]
English is not my first language, but maybe you want to word it as

`see the Demo page`

**Pull request merged**
